version: '2.0'
services:
  slave:
    image: openjdk:jre-alpine
    volumes:
      - '.:/ws'
    working_dir: /ws
    command: 'java -cp ".:lib/*:out/production/distributed_matrix" Slave master'
  master:
    image: openjdk:jre-alpine
    depends_on:
      - slave
    links:
      - slave
    volumes:
      - '.:/ws'
    working_dir: /ws
    command: 'java -cp ".:lib/*:out/production/distributed_matrix" Master 1000'
