version: '2.0'
services:
  slave0:
    image: openjdk:jre-alpine
    volumes:
      - '.:/ws'
    working_dir: /ws
    command: 'java -cp .:lib/scala-library-2.11.11.jar:lib/scala-actors-2.11.2.jar:out/production/distributed_matrix Main --mode slave --slaves 2 --index 0'
  slave1:
    image: openjdk:jre-alpine
    volumes:
      - '.:/ws'
    working_dir: /ws
    command: 'java -cp .:lib/scala-library-2.11.11.jar:lib/scala-actors-2.11.2.jar:out/production/distributed_matrix Main --mode slave --slaves 2 --index 1'
  master:
    image: openjdk:jre-alpine
    depends_on:
      - slave0
      - slave1
    links:
      - slave0
      - slave1
    volumes:
      - '.:/ws'
    working_dir: /ws
    command: "java -cp .:lib/scala-library-2.11.11.jar:lib/scala-actors-2.11.2.jar:out/production/distributed_matrix Main --mode master --slaves 2 --file 100"
