version: '2.0'
services:
  slave0:
    image: openjdk:jre-alpine
    volumes:
      - '.:/ws'
    working_dir: /ws
    command: 'java -cp .:lib/scala-library-2.12.2.jar:out/production/distributed_matrix --mode=slave'
  slave1:
    image: openjdk:jre-alpine
    volumes:
      - '.:/ws'
    working_dir: /ws
    command: 'java -cp .:lib/scala-library-2.12.2.jar:out/production/distributed_matrix --mode=slave'
  master:
    image: openjdk:jre-alpine
    depends_on:
      - slave0
      - slave1
    links:
      - slave0
      - slave1
    volumes:
      - '.:/ws'
    working_dir: /ws
    command: 'java -cp .:lib/scala-library-2.12.2.jar:out/production/distributed_matrix --mode=master --slaves2 ./data/10'
